"""feedback_form_v2_all_sections

Revision ID: 6297b0d20b50
Revises: 009
Create Date: 2026-07-08 14:54:29.091996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6297b0d20b50'
down_revision: Union[str, Sequence[str], None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add all new feedback columns
    op.add_column('feedback', sa.Column('email', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('address', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('spouse_name', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('anniversary_date', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('spouse_birthday', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('child_birthday', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('about_you', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('jewellery_preferences', sa.JSON(), nullable=True))
    op.add_column('feedback', sa.Column('rating_designs', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('rating_quality', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('rating_value', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('rating_staff', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('rating_overall', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('words', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('references', sa.JSON(), nullable=True))
    op.add_column('feedback', sa.Column('join_update_list', sa.Boolean(), nullable=True))
    op.add_column('feedback', sa.Column('visited_recently', sa.Boolean(), nullable=True))
    op.add_column('feedback', sa.Column('can_give_references', sa.Boolean(), nullable=True))
    op.add_column('feedback', sa.Column('next_visit_pref_1', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('next_visit_pref_2', sa.String(), nullable=True))

    # SQLite requires batch mode to drop columns / constraints
    with op.batch_alter_table('feedback', recreate='always') as batch_op:
        batch_op.drop_index('ix_feedback_product_id')
        batch_op.drop_column('feedback_type')
        batch_op.drop_column('experience')
        batch_op.drop_column('description')
        batch_op.drop_column('product_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('product_id', sa.INTEGER(), nullable=True))
    op.add_column('feedback', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('feedback', sa.Column('experience', sa.VARCHAR(), nullable=False))
    op.add_column('feedback', sa.Column('feedback_type', sa.VARCHAR(), nullable=False))
    op.create_foreign_key(None, 'feedback', 'products', ['product_id'], ['id'])
    op.create_index(op.f('ix_feedback_product_id'), 'feedback', ['product_id'], unique=False)
    op.drop_column('feedback', 'next_visit_pref_2')
    op.drop_column('feedback', 'next_visit_pref_1')
    op.drop_column('feedback', 'can_give_references')
    op.drop_column('feedback', 'visited_recently')
    op.drop_column('feedback', 'join_update_list')
    op.drop_column('feedback', 'references')
    op.drop_column('feedback', 'words')
    op.drop_column('feedback', 'rating_overall')
    op.drop_column('feedback', 'rating_staff')
    op.drop_column('feedback', 'rating_value')
    op.drop_column('feedback', 'rating_quality')
    op.drop_column('feedback', 'rating_designs')
    op.drop_column('feedback', 'jewellery_preferences')
    op.drop_column('feedback', 'about_you')
    op.drop_column('feedback', 'child_birthday')
    op.drop_column('feedback', 'spouse_birthday')
    op.drop_column('feedback', 'anniversary_date')
    op.drop_column('feedback', 'spouse_name')
    op.drop_column('feedback', 'address')
    op.drop_column('feedback', 'email')
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_name', sa.VARCHAR(), nullable=False),
    sa.Column('language', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=14), nullable=False),
    sa.Column('use_case', sa.VARCHAR(), nullable=False),
    sa.Column('components_schema', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('meta_template_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_templates_use_case'), 'whatsapp_templates', ['use_case'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_template_name'), 'whatsapp_templates', ['template_name'], unique=1)
    op.create_index(op.f('ix_whatsapp_templates_id'), 'whatsapp_templates', ['id'], unique=False)
    # ### end Alembic commands ###
