"""your migration message

Revision ID: bfc97d0343bd
Revises: 003
Create Date: 2026-02-08 22:41:51.006079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc97d0343bd'
down_revision: Union[str, Sequence[str], None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('thread_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_leads_thread_id'), 'leads', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_thread_id'), table_name='leads')
    op.drop_column('leads', 'thread_id')
    # ### end Alembic commands ###
